apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appsody-frontend
  namespace: kabanero
spec:
  rules:
    - host: "appsody-frontend.csantana-kubecon19.tor01.containers.appdomain.cloud"
      http:
        paths:
          - backend:
              serviceName: appsody-frontend
              servicePort: 3000
